version: '0.1'
# docker-compose pour les tests locaux
services:
  pup:
    build: .
    environment:

      HADOOP_USERNAME: "hadoop"
      HDFS_INPUT_PATH: "/data/knapsack.html"
      HDFS_OUTPUT_PATH: "/data/knapsack.json"
      HADOOP_HOST: "http://host.docker.internal:9870"
    extra_hosts:
      - "host.docker.internal:host-gateway"


